#define WINDOW_WIDTH 1080
#define WINDOW_HEIGHT 600

#define FPS 60
#define FRAME_TARGET_TIME (1000/FPS)

#define MAX_MANAGER_STATIC_OBJ 32
#define MAX_MANAGER_INTER_OBJ 16

#define MAX_GLOBAL_OBJS 512
